# Generated by Django 4.2.6 on 2023-10-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=200)),
                ('admin_mobile', models.CharField(max_length=200)),
                ('admin_email', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(null=True, upload_to='static/')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_mobile', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_image', models.ImageField(upload_to='static/user_images')),
            ],
        ),
        migrations.CreateModel(
            name='userBidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
